// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "NdrFfi",
    platforms: [
        .iOS(.v16),
        .macOS(.v13)
    ],
    products: [
        .library(
            name: "NdrFfi",
            targets: ["NdrFfi"]
        )
    ],
    targets: [
        // Swift bindings generated by uniffi-bindgen
        .target(
            name: "NdrFfi",
            dependencies: ["ndr_ffiFFI"],
            path: "Sources/NdrFfi"
        ),
        // Dynamic XCFramework built from nostr-double-ratchet's pairwise FFI. Keeping
        // this runtime dynamic avoids linking a second Rust static runtime
        // beside Arti's source-built static library.
        .binaryTarget(
            name: "ndr_ffiFFI",
            path: "Frameworks/NdrFfi.xcframework"
        ),
        // Tests
        .testTarget(
            name: "NdrFfiTests",
            dependencies: ["NdrFfi"],
            path: "Tests"
        )
    ]
)
