// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ndr_ffiFFI)
import ndr_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ndr_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ndr_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureNdrFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol PairwiseInviteProtocol: AnyObject, Sendable {

    func getPeerPubkeyHex()  -> String

    func toUrl(root: String) throws  -> String

}
open class PairwiseInvite: PairwiseInviteProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ndr_ffi_fn_clone_pairwiseinvite(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ndr_ffi_fn_free_pairwiseinvite(pointer, $0) }
    }


public static func fromEventJson(eventJson: String)throws  -> PairwiseInvite  {
    return try  FfiConverterTypePairwiseInvite_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_constructor_pairwiseinvite_from_event_json(
        FfiConverterString.lower(eventJson),$0
    )
})
}

public static func fromUrl(url: String)throws  -> PairwiseInvite  {
    return try  FfiConverterTypePairwiseInvite_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_constructor_pairwiseinvite_from_url(
        FfiConverterString.lower(url),$0
    )
})
}



open func getPeerPubkeyHex() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_ndr_ffi_fn_method_pairwiseinvite_get_peer_pubkey_hex(self.uniffiClonePointer(),$0
    )
})
}

open func toUrl(root: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwiseinvite_to_url(self.uniffiClonePointer(),
        FfiConverterString.lower(root),$0
    )
})
}


}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePairwiseInvite: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PairwiseInvite

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PairwiseInvite {
        return PairwiseInvite(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PairwiseInvite) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PairwiseInvite {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PairwiseInvite, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseInvite_lift(_ pointer: UnsafeMutableRawPointer) throws -> PairwiseInvite {
    return try FfiConverterTypePairwiseInvite.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseInvite_lower(_ value: PairwiseInvite) -> UnsafeMutableRawPointer {
    return FfiConverterTypePairwiseInvite.lower(value)
}






public protocol PairwiseManagerProtocol: AnyObject, Sendable {

    func acceptInviteFromEventJson(eventJson: String, authenticatedPeerPubkeyHex: String) throws  -> PairwiseAcceptResult

    func acceptInviteFromUrl(inviteUrl: String, authenticatedPeerPubkeyHex: String) throws  -> PairwiseAcceptResult

    func ackActions(actionIds: [String]) throws

    func currentInviteEventJson() throws  -> String

    func currentInviteUrl(root: String) throws  -> String

    func getOurPubkeyHex() throws  -> String

    func getTotalSessions() throws  -> UInt64

    func knownPeerPubkeys() throws  -> [String]

    func pendingActions() throws  -> [PairwiseAction]

    func pendingActionsAt(nowSeconds: UInt64) throws  -> [PairwiseAction]

    func processEvent(eventJson: String) throws

    func processOutOfBandResponse(eventJson: String, authenticatedPeerPubkeyHex: String) throws

    func retirePeer(peerPubkeyHex: String) throws  -> Bool

    func sendText(peerPubkeyHex: String, text: String, expiresAtSeconds: UInt64?) throws  -> PairwiseSendResult

    func sessionInfo(peerPubkeyHex: String) throws  -> PairwiseSessionInfo?

}
open class PairwiseManager: PairwiseManagerProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ndr_ffi_fn_clone_pairwisemanager(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ndr_ffi_fn_free_pairwisemanager(pointer, $0) }
    }


public static func newWithStoragePath(ourPubkeyHex: String, ourIdentityPrivateKeyHex: String, storagePath: String)throws  -> PairwiseManager  {
    return try  FfiConverterTypePairwiseManager_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_constructor_pairwisemanager_new_with_storage_path(
        FfiConverterString.lower(ourPubkeyHex),
        FfiConverterString.lower(ourIdentityPrivateKeyHex),
        FfiConverterString.lower(storagePath),$0
    )
})
}



open func acceptInviteFromEventJson(eventJson: String, authenticatedPeerPubkeyHex: String)throws  -> PairwiseAcceptResult  {
    return try  FfiConverterTypePairwiseAcceptResult_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_accept_invite_from_event_json(self.uniffiClonePointer(),
        FfiConverterString.lower(eventJson),
        FfiConverterString.lower(authenticatedPeerPubkeyHex),$0
    )
})
}

open func acceptInviteFromUrl(inviteUrl: String, authenticatedPeerPubkeyHex: String)throws  -> PairwiseAcceptResult  {
    return try  FfiConverterTypePairwiseAcceptResult_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_accept_invite_from_url(self.uniffiClonePointer(),
        FfiConverterString.lower(inviteUrl),
        FfiConverterString.lower(authenticatedPeerPubkeyHex),$0
    )
})
}

open func ackActions(actionIds: [String])throws   {try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_ack_actions(self.uniffiClonePointer(),
        FfiConverterSequenceString.lower(actionIds),$0
    )
}
}

open func currentInviteEventJson()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_current_invite_event_json(self.uniffiClonePointer(),$0
    )
})
}

open func currentInviteUrl(root: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_current_invite_url(self.uniffiClonePointer(),
        FfiConverterString.lower(root),$0
    )
})
}

open func getOurPubkeyHex()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_get_our_pubkey_hex(self.uniffiClonePointer(),$0
    )
})
}

open func getTotalSessions()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_get_total_sessions(self.uniffiClonePointer(),$0
    )
})
}

open func knownPeerPubkeys()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_known_peer_pubkeys(self.uniffiClonePointer(),$0
    )
})
}

open func pendingActions()throws  -> [PairwiseAction]  {
    return try  FfiConverterSequenceTypePairwiseAction.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_pending_actions(self.uniffiClonePointer(),$0
    )
})
}

open func pendingActionsAt(nowSeconds: UInt64)throws  -> [PairwiseAction]  {
    return try  FfiConverterSequenceTypePairwiseAction.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_pending_actions_at(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(nowSeconds),$0
    )
})
}

open func processEvent(eventJson: String)throws   {try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_process_event(self.uniffiClonePointer(),
        FfiConverterString.lower(eventJson),$0
    )
}
}

open func processOutOfBandResponse(eventJson: String, authenticatedPeerPubkeyHex: String)throws   {try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_process_out_of_band_response(self.uniffiClonePointer(),
        FfiConverterString.lower(eventJson),
        FfiConverterString.lower(authenticatedPeerPubkeyHex),$0
    )
}
}

open func retirePeer(peerPubkeyHex: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_retire_peer(self.uniffiClonePointer(),
        FfiConverterString.lower(peerPubkeyHex),$0
    )
})
}

open func sendText(peerPubkeyHex: String, text: String, expiresAtSeconds: UInt64?)throws  -> PairwiseSendResult  {
    return try  FfiConverterTypePairwiseSendResult_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_send_text(self.uniffiClonePointer(),
        FfiConverterString.lower(peerPubkeyHex),
        FfiConverterString.lower(text),
        FfiConverterOptionUInt64.lower(expiresAtSeconds),$0
    )
})
}

open func sessionInfo(peerPubkeyHex: String)throws  -> PairwiseSessionInfo?  {
    return try  FfiConverterOptionTypePairwiseSessionInfo.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_pairwisemanager_session_info(self.uniffiClonePointer(),
        FfiConverterString.lower(peerPubkeyHex),$0
    )
})
}


}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePairwiseManager: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PairwiseManager

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PairwiseManager {
        return PairwiseManager(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PairwiseManager) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PairwiseManager {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PairwiseManager, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseManager_lift(_ pointer: UnsafeMutableRawPointer) throws -> PairwiseManager {
    return try FfiConverterTypePairwiseManager.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseManager_lower(_ value: PairwiseManager) -> UnsafeMutableRawPointer {
    return FfiConverterTypePairwiseManager.lower(value)
}




public struct FfiKeyPair {
    public var publicKeyHex: String
    public var privateKeyHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(publicKeyHex: String, privateKeyHex: String) {
        self.publicKeyHex = publicKeyHex
        self.privateKeyHex = privateKeyHex
    }
}

#if compiler(>=6)
extension FfiKeyPair: Sendable {}
#endif


extension FfiKeyPair: Equatable, Hashable {
    public static func ==(lhs: FfiKeyPair, rhs: FfiKeyPair) -> Bool {
        if lhs.publicKeyHex != rhs.publicKeyHex {
            return false
        }
        if lhs.privateKeyHex != rhs.privateKeyHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(publicKeyHex)
        hasher.combine(privateKeyHex)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiKeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiKeyPair {
        return
            try FfiKeyPair(
                publicKeyHex: FfiConverterString.read(from: &buf),
                privateKeyHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiKeyPair, into buf: inout [UInt8]) {
        FfiConverterString.write(value.publicKeyHex, into: &buf)
        FfiConverterString.write(value.privateKeyHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiKeyPair_lift(_ buf: RustBuffer) throws -> FfiKeyPair {
    return try FfiConverterTypeFfiKeyPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiKeyPair_lower(_ value: FfiKeyPair) -> RustBuffer {
    return FfiConverterTypeFfiKeyPair.lower(value)
}


public struct PairwiseAcceptResult {
    public var peerPubkeyHex: String
    public var createdNewSession: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(peerPubkeyHex: String, createdNewSession: Bool) {
        self.peerPubkeyHex = peerPubkeyHex
        self.createdNewSession = createdNewSession
    }
}

#if compiler(>=6)
extension PairwiseAcceptResult: Sendable {}
#endif


extension PairwiseAcceptResult: Equatable, Hashable {
    public static func ==(lhs: PairwiseAcceptResult, rhs: PairwiseAcceptResult) -> Bool {
        if lhs.peerPubkeyHex != rhs.peerPubkeyHex {
            return false
        }
        if lhs.createdNewSession != rhs.createdNewSession {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(peerPubkeyHex)
        hasher.combine(createdNewSession)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePairwiseAcceptResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PairwiseAcceptResult {
        return
            try PairwiseAcceptResult(
                peerPubkeyHex: FfiConverterString.read(from: &buf),
                createdNewSession: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PairwiseAcceptResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.peerPubkeyHex, into: &buf)
        FfiConverterBool.write(value.createdNewSession, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseAcceptResult_lift(_ buf: RustBuffer) throws -> PairwiseAcceptResult {
    return try FfiConverterTypePairwiseAcceptResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseAcceptResult_lower(_ value: PairwiseAcceptResult) -> RustBuffer {
    return FfiConverterTypePairwiseAcceptResult.lower(value)
}


public struct PairwiseAction {
    public var actionId: String
    public var kind: String
    public var sessionId: String?
    public var subscriptionId: String?
    public var filterJson: String?
    public var eventJson: String?
    public var peerPubkeyHex: String?
    public var innerEventJson: String?
    public var innerEventId: String?
    public var outerEventId: String?
    public var expiresAtSeconds: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(actionId: String, kind: String, sessionId: String?, subscriptionId: String?, filterJson: String?, eventJson: String?, peerPubkeyHex: String?, innerEventJson: String?, innerEventId: String?, outerEventId: String?, expiresAtSeconds: UInt64?) {
        self.actionId = actionId
        self.kind = kind
        self.sessionId = sessionId
        self.subscriptionId = subscriptionId
        self.filterJson = filterJson
        self.eventJson = eventJson
        self.peerPubkeyHex = peerPubkeyHex
        self.innerEventJson = innerEventJson
        self.innerEventId = innerEventId
        self.outerEventId = outerEventId
        self.expiresAtSeconds = expiresAtSeconds
    }
}

#if compiler(>=6)
extension PairwiseAction: Sendable {}
#endif


extension PairwiseAction: Equatable, Hashable {
    public static func ==(lhs: PairwiseAction, rhs: PairwiseAction) -> Bool {
        if lhs.actionId != rhs.actionId {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.subscriptionId != rhs.subscriptionId {
            return false
        }
        if lhs.filterJson != rhs.filterJson {
            return false
        }
        if lhs.eventJson != rhs.eventJson {
            return false
        }
        if lhs.peerPubkeyHex != rhs.peerPubkeyHex {
            return false
        }
        if lhs.innerEventJson != rhs.innerEventJson {
            return false
        }
        if lhs.innerEventId != rhs.innerEventId {
            return false
        }
        if lhs.outerEventId != rhs.outerEventId {
            return false
        }
        if lhs.expiresAtSeconds != rhs.expiresAtSeconds {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(actionId)
        hasher.combine(kind)
        hasher.combine(sessionId)
        hasher.combine(subscriptionId)
        hasher.combine(filterJson)
        hasher.combine(eventJson)
        hasher.combine(peerPubkeyHex)
        hasher.combine(innerEventJson)
        hasher.combine(innerEventId)
        hasher.combine(outerEventId)
        hasher.combine(expiresAtSeconds)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePairwiseAction: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PairwiseAction {
        return
            try PairwiseAction(
                actionId: FfiConverterString.read(from: &buf),
                kind: FfiConverterString.read(from: &buf),
                sessionId: FfiConverterOptionString.read(from: &buf),
                subscriptionId: FfiConverterOptionString.read(from: &buf),
                filterJson: FfiConverterOptionString.read(from: &buf),
                eventJson: FfiConverterOptionString.read(from: &buf),
                peerPubkeyHex: FfiConverterOptionString.read(from: &buf),
                innerEventJson: FfiConverterOptionString.read(from: &buf),
                innerEventId: FfiConverterOptionString.read(from: &buf),
                outerEventId: FfiConverterOptionString.read(from: &buf),
                expiresAtSeconds: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: PairwiseAction, into buf: inout [UInt8]) {
        FfiConverterString.write(value.actionId, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterOptionString.write(value.sessionId, into: &buf)
        FfiConverterOptionString.write(value.subscriptionId, into: &buf)
        FfiConverterOptionString.write(value.filterJson, into: &buf)
        FfiConverterOptionString.write(value.eventJson, into: &buf)
        FfiConverterOptionString.write(value.peerPubkeyHex, into: &buf)
        FfiConverterOptionString.write(value.innerEventJson, into: &buf)
        FfiConverterOptionString.write(value.innerEventId, into: &buf)
        FfiConverterOptionString.write(value.outerEventId, into: &buf)
        FfiConverterOptionUInt64.write(value.expiresAtSeconds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseAction_lift(_ buf: RustBuffer) throws -> PairwiseAction {
    return try FfiConverterTypePairwiseAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseAction_lower(_ value: PairwiseAction) -> RustBuffer {
    return FfiConverterTypePairwiseAction.lower(value)
}


public struct PairwiseSendResult {
    public var innerEventId: String
    public var outerEventId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(innerEventId: String, outerEventId: String) {
        self.innerEventId = innerEventId
        self.outerEventId = outerEventId
    }
}

#if compiler(>=6)
extension PairwiseSendResult: Sendable {}
#endif


extension PairwiseSendResult: Equatable, Hashable {
    public static func ==(lhs: PairwiseSendResult, rhs: PairwiseSendResult) -> Bool {
        if lhs.innerEventId != rhs.innerEventId {
            return false
        }
        if lhs.outerEventId != rhs.outerEventId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(innerEventId)
        hasher.combine(outerEventId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePairwiseSendResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PairwiseSendResult {
        return
            try PairwiseSendResult(
                innerEventId: FfiConverterString.read(from: &buf),
                outerEventId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PairwiseSendResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.innerEventId, into: &buf)
        FfiConverterString.write(value.outerEventId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseSendResult_lift(_ buf: RustBuffer) throws -> PairwiseSendResult {
    return try FfiConverterTypePairwiseSendResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseSendResult_lower(_ value: PairwiseSendResult) -> RustBuffer {
    return FfiConverterTypePairwiseSendResult.lower(value)
}


public struct PairwiseSessionInfo {
    public var sendReady: Bool
    public var receiveReady: Bool
    public var trackedSenderPubkeys: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sendReady: Bool, receiveReady: Bool, trackedSenderPubkeys: [String]) {
        self.sendReady = sendReady
        self.receiveReady = receiveReady
        self.trackedSenderPubkeys = trackedSenderPubkeys
    }
}

#if compiler(>=6)
extension PairwiseSessionInfo: Sendable {}
#endif


extension PairwiseSessionInfo: Equatable, Hashable {
    public static func ==(lhs: PairwiseSessionInfo, rhs: PairwiseSessionInfo) -> Bool {
        if lhs.sendReady != rhs.sendReady {
            return false
        }
        if lhs.receiveReady != rhs.receiveReady {
            return false
        }
        if lhs.trackedSenderPubkeys != rhs.trackedSenderPubkeys {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sendReady)
        hasher.combine(receiveReady)
        hasher.combine(trackedSenderPubkeys)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePairwiseSessionInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PairwiseSessionInfo {
        return
            try PairwiseSessionInfo(
                sendReady: FfiConverterBool.read(from: &buf),
                receiveReady: FfiConverterBool.read(from: &buf),
                trackedSenderPubkeys: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: PairwiseSessionInfo, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.sendReady, into: &buf)
        FfiConverterBool.write(value.receiveReady, into: &buf)
        FfiConverterSequenceString.write(value.trackedSenderPubkeys, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseSessionInfo_lift(_ buf: RustBuffer) throws -> PairwiseSessionInfo {
    return try FfiConverterTypePairwiseSessionInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseSessionInfo_lower(_ value: PairwiseSessionInfo) -> RustBuffer {
    return FfiConverterTypePairwiseSessionInfo.lower(value)
}


public enum NdrError: Swift.Error {



    case InvalidKey(String
    )
    case InvalidEvent(String
    )
    case PeerMismatch(String
    )
    case SessionNotReady(String
    )
    case QueueFull(String
    )
    case Storage(String
    )
    case CryptoFailure(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNdrError: FfiConverterRustBuffer {
    typealias SwiftType = NdrError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NdrError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .InvalidKey(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidEvent(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .PeerMismatch(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .SessionNotReady(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .QueueFull(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .Storage(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .CryptoFailure(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NdrError, into buf: inout [UInt8]) {
        switch value {





        case let .InvalidKey(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)


        case let .InvalidEvent(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)


        case let .PeerMismatch(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)


        case let .SessionNotReady(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)


        case let .QueueFull(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)


        case let .Storage(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)


        case let .CryptoFailure(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNdrError_lift(_ buf: RustBuffer) throws -> NdrError {
    return try FfiConverterTypeNdrError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNdrError_lower(_ value: NdrError) -> RustBuffer {
    return FfiConverterTypeNdrError.lower(value)
}


extension NdrError: Equatable, Hashable {}




extension NdrError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePairwiseSessionInfo: FfiConverterRustBuffer {
    typealias SwiftType = PairwiseSessionInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePairwiseSessionInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePairwiseSessionInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePairwiseAction: FfiConverterRustBuffer {
    typealias SwiftType = [PairwiseAction]

    public static func write(_ value: [PairwiseAction], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePairwiseAction.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PairwiseAction] {
        let len: Int32 = try readInt(&buf)
        var seq = [PairwiseAction]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePairwiseAction.read(from: &buf))
        }
        return seq
    }
}
public func derivePublicKey(privateKeyHex: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_func_derive_public_key(
        FfiConverterString.lower(privateKeyHex),$0
    )
})
}
public func generateKeypair() -> FfiKeyPair  {
    return try!  FfiConverterTypeFfiKeyPair_lift(try! rustCall() {
    uniffi_ndr_ffi_fn_func_generate_keypair($0
    )
})
}
public func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_ndr_ffi_fn_func_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ndr_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ndr_ffi_checksum_func_derive_public_key() != 22065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_func_generate_keypair() != 57537) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_func_version() != 35402) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwiseinvite_get_peer_pubkey_hex() != 25596) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwiseinvite_to_url() != 1141) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_accept_invite_from_event_json() != 42574) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_accept_invite_from_url() != 29995) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_ack_actions() != 17265) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_current_invite_event_json() != 41966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_current_invite_url() != 50454) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_get_our_pubkey_hex() != 24347) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_get_total_sessions() != 5478) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_known_peer_pubkeys() != 21367) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_pending_actions() != 4469) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_pending_actions_at() != 26221) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_process_event() != 51097) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_process_out_of_band_response() != 48382) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_retire_peer() != 12247) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_send_text() != 20592) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_pairwisemanager_session_info() != 49395) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_constructor_pairwiseinvite_from_event_json() != 9371) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_constructor_pairwiseinvite_from_url() != 12100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_constructor_pairwisemanager_new_with_storage_path() != 24319) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureNdrFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all