// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ndr_ffiFFI)
import ndr_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ndr_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ndr_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureNdrFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol InviteHandleProtocol: AnyObject, Sendable {

    func getInviterPubkeyHex()  -> String

    func getOwnerPubkeyHex() throws  -> String

    func toUrl(root: String) throws  -> String

}
open class InviteHandle: InviteHandleProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ndr_ffi_fn_clone_invitehandle(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ndr_ffi_fn_free_invitehandle(pointer, $0) }
    }


public static func fromEventJson(eventJson: String)throws  -> InviteHandle  {
    return try  FfiConverterTypeInviteHandle_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_constructor_invitehandle_from_event_json(
        FfiConverterString.lower(eventJson),$0
    )
})
}

public static func fromUrl(url: String)throws  -> InviteHandle  {
    return try  FfiConverterTypeInviteHandle_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_constructor_invitehandle_from_url(
        FfiConverterString.lower(url),$0
    )
})
}



open func getInviterPubkeyHex() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_ndr_ffi_fn_method_invitehandle_get_inviter_pubkey_hex(self.uniffiClonePointer(),$0
    )
})
}

open func getOwnerPubkeyHex()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_invitehandle_get_owner_pubkey_hex(self.uniffiClonePointer(),$0
    )
})
}

open func toUrl(root: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_invitehandle_to_url(self.uniffiClonePointer(),
        FfiConverterString.lower(root),$0
    )
})
}


}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInviteHandle: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = InviteHandle

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> InviteHandle {
        return InviteHandle(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: InviteHandle) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InviteHandle {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: InviteHandle, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInviteHandle_lift(_ pointer: UnsafeMutableRawPointer) throws -> InviteHandle {
    return try FfiConverterTypeInviteHandle.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInviteHandle_lower(_ value: InviteHandle) -> UnsafeMutableRawPointer {
    return FfiConverterTypeInviteHandle.lower(value)
}






public protocol SessionManagerHandleProtocol: AnyObject, Sendable {

    func acceptInviteFromEventJson(eventJson: String, ownerPubkeyHintHex: String?) throws  -> SessionManagerAcceptInviteResult

    func acceptInviteFromUrl(inviteUrl: String, ownerPubkeyHintHex: String?) throws  -> SessionManagerAcceptInviteResult

    func drainEvents() throws  -> [PubSubEvent]

    func getActiveSessionState(peerPubkeyHex: String) throws  -> String?

    func getDeviceId()  -> String

    func getMessagePushAuthorPubkeys(peerOwnerPubkeyHex: String) throws  -> [String]

    func getMessagePushSessionStates(peerOwnerPubkeyHex: String) throws  -> [MessagePushSessionStateResult]

    func getOurPubkeyHex()  -> String

    func getOwnerPubkeyHex()  -> String

    func getTotalSessions()  -> UInt64

    func `init`() throws

    func knownPeerOwnerPubkeys()  -> [String]

    func processEvent(eventJson: String) throws

    func processOutOfBandResponse(eventJson: String, expectedOwnerPubkeyHex: String) throws

    func sendText(recipientPubkeyHex: String, text: String, expiresAtSeconds: UInt64?) throws  -> [String]

    func sendTextWithInnerId(recipientPubkeyHex: String, text: String, expiresAtSeconds: UInt64?) throws  -> SendTextResult

    func setupUser(userPubkeyHex: String) throws

}
open class SessionManagerHandle: SessionManagerHandleProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ndr_ffi_fn_clone_sessionmanagerhandle(self.pointer, $0) }
    }
public convenience init(ourPubkeyHex: String, ourIdentityPrivkeyHex: String, deviceId: String, ownerPubkeyHex: String?)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_constructor_sessionmanagerhandle_new(
        FfiConverterString.lower(ourPubkeyHex),
        FfiConverterString.lower(ourIdentityPrivkeyHex),
        FfiConverterString.lower(deviceId),
        FfiConverterOptionString.lower(ownerPubkeyHex),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ndr_ffi_fn_free_sessionmanagerhandle(pointer, $0) }
    }


public static func newWithStoragePath(ourPubkeyHex: String, ourIdentityPrivkeyHex: String, deviceId: String, storagePath: String, ownerPubkeyHex: String?)throws  -> SessionManagerHandle  {
    return try  FfiConverterTypeSessionManagerHandle_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_constructor_sessionmanagerhandle_new_with_storage_path(
        FfiConverterString.lower(ourPubkeyHex),
        FfiConverterString.lower(ourIdentityPrivkeyHex),
        FfiConverterString.lower(deviceId),
        FfiConverterString.lower(storagePath),
        FfiConverterOptionString.lower(ownerPubkeyHex),$0
    )
})
}



open func acceptInviteFromEventJson(eventJson: String, ownerPubkeyHintHex: String?)throws  -> SessionManagerAcceptInviteResult  {
    return try  FfiConverterTypeSessionManagerAcceptInviteResult_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_accept_invite_from_event_json(self.uniffiClonePointer(),
        FfiConverterString.lower(eventJson),
        FfiConverterOptionString.lower(ownerPubkeyHintHex),$0
    )
})
}

open func acceptInviteFromUrl(inviteUrl: String, ownerPubkeyHintHex: String?)throws  -> SessionManagerAcceptInviteResult  {
    return try  FfiConverterTypeSessionManagerAcceptInviteResult_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_accept_invite_from_url(self.uniffiClonePointer(),
        FfiConverterString.lower(inviteUrl),
        FfiConverterOptionString.lower(ownerPubkeyHintHex),$0
    )
})
}

open func drainEvents()throws  -> [PubSubEvent]  {
    return try  FfiConverterSequenceTypePubSubEvent.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_drain_events(self.uniffiClonePointer(),$0
    )
})
}

open func getActiveSessionState(peerPubkeyHex: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_get_active_session_state(self.uniffiClonePointer(),
        FfiConverterString.lower(peerPubkeyHex),$0
    )
})
}

open func getDeviceId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_get_device_id(self.uniffiClonePointer(),$0
    )
})
}

open func getMessagePushAuthorPubkeys(peerOwnerPubkeyHex: String)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_get_message_push_author_pubkeys(self.uniffiClonePointer(),
        FfiConverterString.lower(peerOwnerPubkeyHex),$0
    )
})
}

open func getMessagePushSessionStates(peerOwnerPubkeyHex: String)throws  -> [MessagePushSessionStateResult]  {
    return try  FfiConverterSequenceTypeMessagePushSessionStateResult.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_get_message_push_session_states(self.uniffiClonePointer(),
        FfiConverterString.lower(peerOwnerPubkeyHex),$0
    )
})
}

open func getOurPubkeyHex() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_get_our_pubkey_hex(self.uniffiClonePointer(),$0
    )
})
}

open func getOwnerPubkeyHex() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_get_owner_pubkey_hex(self.uniffiClonePointer(),$0
    )
})
}

open func getTotalSessions() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_get_total_sessions(self.uniffiClonePointer(),$0
    )
})
}

open func `init`()throws   {try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_init(self.uniffiClonePointer(),$0
    )
}
}

open func knownPeerOwnerPubkeys() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_known_peer_owner_pubkeys(self.uniffiClonePointer(),$0
    )
})
}

open func processEvent(eventJson: String)throws   {try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_process_event(self.uniffiClonePointer(),
        FfiConverterString.lower(eventJson),$0
    )
}
}

open func processOutOfBandResponse(eventJson: String, expectedOwnerPubkeyHex: String)throws   {try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_process_out_of_band_response(self.uniffiClonePointer(),
        FfiConverterString.lower(eventJson),
        FfiConverterString.lower(expectedOwnerPubkeyHex),$0
    )
}
}

open func sendText(recipientPubkeyHex: String, text: String, expiresAtSeconds: UInt64?)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_send_text(self.uniffiClonePointer(),
        FfiConverterString.lower(recipientPubkeyHex),
        FfiConverterString.lower(text),
        FfiConverterOptionUInt64.lower(expiresAtSeconds),$0
    )
})
}

open func sendTextWithInnerId(recipientPubkeyHex: String, text: String, expiresAtSeconds: UInt64?)throws  -> SendTextResult  {
    return try  FfiConverterTypeSendTextResult_lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_send_text_with_inner_id(self.uniffiClonePointer(),
        FfiConverterString.lower(recipientPubkeyHex),
        FfiConverterString.lower(text),
        FfiConverterOptionUInt64.lower(expiresAtSeconds),$0
    )
})
}

open func setupUser(userPubkeyHex: String)throws   {try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_method_sessionmanagerhandle_setup_user(self.uniffiClonePointer(),
        FfiConverterString.lower(userPubkeyHex),$0
    )
}
}


}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionManagerHandle: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SessionManagerHandle

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SessionManagerHandle {
        return SessionManagerHandle(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SessionManagerHandle) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionManagerHandle {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SessionManagerHandle, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionManagerHandle_lift(_ pointer: UnsafeMutableRawPointer) throws -> SessionManagerHandle {
    return try FfiConverterTypeSessionManagerHandle.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionManagerHandle_lower(_ value: SessionManagerHandle) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSessionManagerHandle.lower(value)
}




public struct FfiKeyPair {
    public var publicKeyHex: String
    public var privateKeyHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(publicKeyHex: String, privateKeyHex: String) {
        self.publicKeyHex = publicKeyHex
        self.privateKeyHex = privateKeyHex
    }
}

#if compiler(>=6)
extension FfiKeyPair: Sendable {}
#endif


extension FfiKeyPair: Equatable, Hashable {
    public static func ==(lhs: FfiKeyPair, rhs: FfiKeyPair) -> Bool {
        if lhs.publicKeyHex != rhs.publicKeyHex {
            return false
        }
        if lhs.privateKeyHex != rhs.privateKeyHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(publicKeyHex)
        hasher.combine(privateKeyHex)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiKeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiKeyPair {
        return
            try FfiKeyPair(
                publicKeyHex: FfiConverterString.read(from: &buf),
                privateKeyHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiKeyPair, into buf: inout [UInt8]) {
        FfiConverterString.write(value.publicKeyHex, into: &buf)
        FfiConverterString.write(value.privateKeyHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiKeyPair_lift(_ buf: RustBuffer) throws -> FfiKeyPair {
    return try FfiConverterTypeFfiKeyPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiKeyPair_lower(_ value: FfiKeyPair) -> RustBuffer {
    return FfiConverterTypeFfiKeyPair.lower(value)
}


public struct MessagePushSessionStateResult {
    public var stateJson: String
    public var trackedSenderPubkeys: [String]
    public var hasReceivingCapability: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(stateJson: String, trackedSenderPubkeys: [String], hasReceivingCapability: Bool) {
        self.stateJson = stateJson
        self.trackedSenderPubkeys = trackedSenderPubkeys
        self.hasReceivingCapability = hasReceivingCapability
    }
}

#if compiler(>=6)
extension MessagePushSessionStateResult: Sendable {}
#endif


extension MessagePushSessionStateResult: Equatable, Hashable {
    public static func ==(lhs: MessagePushSessionStateResult, rhs: MessagePushSessionStateResult) -> Bool {
        if lhs.stateJson != rhs.stateJson {
            return false
        }
        if lhs.trackedSenderPubkeys != rhs.trackedSenderPubkeys {
            return false
        }
        if lhs.hasReceivingCapability != rhs.hasReceivingCapability {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(stateJson)
        hasher.combine(trackedSenderPubkeys)
        hasher.combine(hasReceivingCapability)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessagePushSessionStateResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessagePushSessionStateResult {
        return
            try MessagePushSessionStateResult(
                stateJson: FfiConverterString.read(from: &buf),
                trackedSenderPubkeys: FfiConverterSequenceString.read(from: &buf),
                hasReceivingCapability: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MessagePushSessionStateResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.stateJson, into: &buf)
        FfiConverterSequenceString.write(value.trackedSenderPubkeys, into: &buf)
        FfiConverterBool.write(value.hasReceivingCapability, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessagePushSessionStateResult_lift(_ buf: RustBuffer) throws -> MessagePushSessionStateResult {
    return try FfiConverterTypeMessagePushSessionStateResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessagePushSessionStateResult_lower(_ value: MessagePushSessionStateResult) -> RustBuffer {
    return FfiConverterTypeMessagePushSessionStateResult.lower(value)
}


public struct PubSubEvent {
    public var kind: String
    public var subid: String?
    public var filterJson: String?
    public var eventJson: String?
    public var senderPubkeyHex: String?
    public var senderDevicePubkeyHex: String?
    public var conversationOwnerPubkeyHex: String?
    public var content: String?
    public var eventId: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: String, subid: String?, filterJson: String?, eventJson: String?, senderPubkeyHex: String?, senderDevicePubkeyHex: String?, conversationOwnerPubkeyHex: String?, content: String?, eventId: String?) {
        self.kind = kind
        self.subid = subid
        self.filterJson = filterJson
        self.eventJson = eventJson
        self.senderPubkeyHex = senderPubkeyHex
        self.senderDevicePubkeyHex = senderDevicePubkeyHex
        self.conversationOwnerPubkeyHex = conversationOwnerPubkeyHex
        self.content = content
        self.eventId = eventId
    }
}

#if compiler(>=6)
extension PubSubEvent: Sendable {}
#endif


extension PubSubEvent: Equatable, Hashable {
    public static func ==(lhs: PubSubEvent, rhs: PubSubEvent) -> Bool {
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.subid != rhs.subid {
            return false
        }
        if lhs.filterJson != rhs.filterJson {
            return false
        }
        if lhs.eventJson != rhs.eventJson {
            return false
        }
        if lhs.senderPubkeyHex != rhs.senderPubkeyHex {
            return false
        }
        if lhs.senderDevicePubkeyHex != rhs.senderDevicePubkeyHex {
            return false
        }
        if lhs.conversationOwnerPubkeyHex != rhs.conversationOwnerPubkeyHex {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        if lhs.eventId != rhs.eventId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(kind)
        hasher.combine(subid)
        hasher.combine(filterJson)
        hasher.combine(eventJson)
        hasher.combine(senderPubkeyHex)
        hasher.combine(senderDevicePubkeyHex)
        hasher.combine(conversationOwnerPubkeyHex)
        hasher.combine(content)
        hasher.combine(eventId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePubSubEvent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PubSubEvent {
        return
            try PubSubEvent(
                kind: FfiConverterString.read(from: &buf),
                subid: FfiConverterOptionString.read(from: &buf),
                filterJson: FfiConverterOptionString.read(from: &buf),
                eventJson: FfiConverterOptionString.read(from: &buf),
                senderPubkeyHex: FfiConverterOptionString.read(from: &buf),
                senderDevicePubkeyHex: FfiConverterOptionString.read(from: &buf),
                conversationOwnerPubkeyHex: FfiConverterOptionString.read(from: &buf),
                content: FfiConverterOptionString.read(from: &buf),
                eventId: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: PubSubEvent, into buf: inout [UInt8]) {
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterOptionString.write(value.subid, into: &buf)
        FfiConverterOptionString.write(value.filterJson, into: &buf)
        FfiConverterOptionString.write(value.eventJson, into: &buf)
        FfiConverterOptionString.write(value.senderPubkeyHex, into: &buf)
        FfiConverterOptionString.write(value.senderDevicePubkeyHex, into: &buf)
        FfiConverterOptionString.write(value.conversationOwnerPubkeyHex, into: &buf)
        FfiConverterOptionString.write(value.content, into: &buf)
        FfiConverterOptionString.write(value.eventId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePubSubEvent_lift(_ buf: RustBuffer) throws -> PubSubEvent {
    return try FfiConverterTypePubSubEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePubSubEvent_lower(_ value: PubSubEvent) -> RustBuffer {
    return FfiConverterTypePubSubEvent.lower(value)
}


public struct SendTextResult {
    public var innerId: String
    public var outerEventIds: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(innerId: String, outerEventIds: [String]) {
        self.innerId = innerId
        self.outerEventIds = outerEventIds
    }
}

#if compiler(>=6)
extension SendTextResult: Sendable {}
#endif


extension SendTextResult: Equatable, Hashable {
    public static func ==(lhs: SendTextResult, rhs: SendTextResult) -> Bool {
        if lhs.innerId != rhs.innerId {
            return false
        }
        if lhs.outerEventIds != rhs.outerEventIds {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(innerId)
        hasher.combine(outerEventIds)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendTextResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendTextResult {
        return
            try SendTextResult(
                innerId: FfiConverterString.read(from: &buf),
                outerEventIds: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: SendTextResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.innerId, into: &buf)
        FfiConverterSequenceString.write(value.outerEventIds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendTextResult_lift(_ buf: RustBuffer) throws -> SendTextResult {
    return try FfiConverterTypeSendTextResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendTextResult_lower(_ value: SendTextResult) -> RustBuffer {
    return FfiConverterTypeSendTextResult.lower(value)
}


public struct SessionManagerAcceptInviteResult {
    public var ownerPubkeyHex: String
    public var inviterDevicePubkeyHex: String
    public var deviceId: String
    public var createdNewSession: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ownerPubkeyHex: String, inviterDevicePubkeyHex: String, deviceId: String, createdNewSession: Bool) {
        self.ownerPubkeyHex = ownerPubkeyHex
        self.inviterDevicePubkeyHex = inviterDevicePubkeyHex
        self.deviceId = deviceId
        self.createdNewSession = createdNewSession
    }
}

#if compiler(>=6)
extension SessionManagerAcceptInviteResult: Sendable {}
#endif


extension SessionManagerAcceptInviteResult: Equatable, Hashable {
    public static func ==(lhs: SessionManagerAcceptInviteResult, rhs: SessionManagerAcceptInviteResult) -> Bool {
        if lhs.ownerPubkeyHex != rhs.ownerPubkeyHex {
            return false
        }
        if lhs.inviterDevicePubkeyHex != rhs.inviterDevicePubkeyHex {
            return false
        }
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.createdNewSession != rhs.createdNewSession {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(ownerPubkeyHex)
        hasher.combine(inviterDevicePubkeyHex)
        hasher.combine(deviceId)
        hasher.combine(createdNewSession)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionManagerAcceptInviteResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionManagerAcceptInviteResult {
        return
            try SessionManagerAcceptInviteResult(
                ownerPubkeyHex: FfiConverterString.read(from: &buf),
                inviterDevicePubkeyHex: FfiConverterString.read(from: &buf),
                deviceId: FfiConverterString.read(from: &buf),
                createdNewSession: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: SessionManagerAcceptInviteResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.ownerPubkeyHex, into: &buf)
        FfiConverterString.write(value.inviterDevicePubkeyHex, into: &buf)
        FfiConverterString.write(value.deviceId, into: &buf)
        FfiConverterBool.write(value.createdNewSession, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionManagerAcceptInviteResult_lift(_ buf: RustBuffer) throws -> SessionManagerAcceptInviteResult {
    return try FfiConverterTypeSessionManagerAcceptInviteResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionManagerAcceptInviteResult_lower(_ value: SessionManagerAcceptInviteResult) -> RustBuffer {
    return FfiConverterTypeSessionManagerAcceptInviteResult.lower(value)
}


public enum NdrError: Swift.Error {



    case InvalidKey(String
    )
    case InvalidEvent(String
    )
    case CryptoFailure(String
    )
    case StateMismatch(String
    )
    case Serialization(String
    )
    case InviteError(String
    )
    case SessionNotReady(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNdrError: FfiConverterRustBuffer {
    typealias SwiftType = NdrError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NdrError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .InvalidKey(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidEvent(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .CryptoFailure(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .StateMismatch(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .Serialization(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .InviteError(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .SessionNotReady(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NdrError, into buf: inout [UInt8]) {
        switch value {





        case let .InvalidKey(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)


        case let .InvalidEvent(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)


        case let .CryptoFailure(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)


        case let .StateMismatch(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)


        case let .Serialization(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)


        case let .InviteError(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)


        case let .SessionNotReady(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNdrError_lift(_ buf: RustBuffer) throws -> NdrError {
    return try FfiConverterTypeNdrError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNdrError_lower(_ value: NdrError) -> RustBuffer {
    return FfiConverterTypeNdrError.lower(value)
}


extension NdrError: Equatable, Hashable {}




extension NdrError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMessagePushSessionStateResult: FfiConverterRustBuffer {
    typealias SwiftType = [MessagePushSessionStateResult]

    public static func write(_ value: [MessagePushSessionStateResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMessagePushSessionStateResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MessagePushSessionStateResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [MessagePushSessionStateResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMessagePushSessionStateResult.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePubSubEvent: FfiConverterRustBuffer {
    typealias SwiftType = [PubSubEvent]

    public static func write(_ value: [PubSubEvent], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePubSubEvent.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PubSubEvent] {
        let len: Int32 = try readInt(&buf)
        var seq = [PubSubEvent]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePubSubEvent.read(from: &buf))
        }
        return seq
    }
}
public func derivePublicKey(privkeyHex: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNdrError_lift) {
    uniffi_ndr_ffi_fn_func_derive_public_key(
        FfiConverterString.lower(privkeyHex),$0
    )
})
}
public func generateKeypair() -> FfiKeyPair  {
    return try!  FfiConverterTypeFfiKeyPair_lift(try! rustCall() {
    uniffi_ndr_ffi_fn_func_generate_keypair($0
    )
})
}
public func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_ndr_ffi_fn_func_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ndr_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ndr_ffi_checksum_func_derive_public_key() != 46297) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_func_generate_keypair() != 57537) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_func_version() != 35402) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_invitehandle_get_inviter_pubkey_hex() != 62322) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_invitehandle_get_owner_pubkey_hex() != 17484) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_invitehandle_to_url() != 41511) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_accept_invite_from_event_json() != 39696) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_accept_invite_from_url() != 49858) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_drain_events() != 31848) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_get_active_session_state() != 4999) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_get_device_id() != 8402) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_get_message_push_author_pubkeys() != 45983) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_get_message_push_session_states() != 64635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_get_our_pubkey_hex() != 19398) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_get_owner_pubkey_hex() != 49647) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_get_total_sessions() != 21120) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_init() != 25634) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_known_peer_owner_pubkeys() != 31004) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_process_event() != 18483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_process_out_of_band_response() != 48675) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_send_text() != 56962) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_send_text_with_inner_id() != 55155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_method_sessionmanagerhandle_setup_user() != 41291) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_constructor_invitehandle_from_event_json() != 46387) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_constructor_invitehandle_from_url() != 28197) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_constructor_sessionmanagerhandle_new() != 47765) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ndr_ffi_checksum_constructor_sessionmanagerhandle_new_with_storage_path() != 5699) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureNdrFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all